# Generated by Django 3.2.5 on 2021-12-07 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0003_auto_20211206_1500"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="drink",
            options={
                "verbose_name": "Drink Option",
                "verbose_name_plural": "Drink Options",
            },
        ),
    ]
