# Generated by Django 3.2.5 on 2021-12-07 07:54

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0004_alter_drink_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Size",
            fields=[
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("size_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "description",
                    models.CharField(
                        choices=[
                            ("XL", "XLarge"),
                            ("L", "Large"),
                            ("S", "Small"),
                            ("M", "Medium"),
                        ],
                        max_length=20,
                        verbose_name="Name",
                    ),
                ),
                ("constant_addition", models.IntegerField(default=30)),
            ],
            options={
                "verbose_name": "サイズ",
                "verbose_name_plural": "サイズ",
                "db_table": "cafe_size",
            },
        ),
        migrations.AddField(
            model_name="drink",
            name="size",
            field=models.ManyToManyField(
                blank=True, related_name="size", to="cafe.Size"
            ),
        ),
    ]
