# Generated by Django 3.2.5 on 2021-12-07 08:25

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0005_auto_20211207_1654"),
    ]

    operations = [
        migrations.AlterField(
            model_name="size",
            name="description",
            field=models.CharField(
                choices=[
                    ("XL", "XLarge"),
                    ("L", "Large"),
                    ("S", "Small"),
                    ("M", "Medium"),
                ],
                max_length=20,
                unique=True,
                verbose_name="Name",
            ),
        ),
    ]
