# Generated by Django 3.2.5 on 2021-12-07 09:03

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0006_alter_size_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topping",
            fields=[
                ("topping_id", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=30)),
                ("Addition Fee", models.IntegerField(default=50)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "トッピング",
                "verbose_name_plural": "トッピング",
                "db_table": "cafe_topping",
            },
        ),
    ]
