# Generated by Django 3.2.5 on 2021-12-07 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0007_topping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topping',
            old_name='Name',
            new_name='description',
        ),
    ]
