version: 2.1
orbs:
  gh: circleci/github-cli@2.0
workflows:
  gh-workflow:
    jobs:
      - create-a-pr:
            context:
               - GITHUB_TOKEN
            filters:
              branches:
                only:
                  - master

jobs:
  create-a-pr:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - gh/setup
      - run:
          command: |
              git config --global user.name "circleci"
              git config --global user.email "test@test.gg"
              gh pr create -B prod -t "test prod pl"
          name: Create Pull Request For Production






