version: 2.1
orbs:
  gh: circleci/github-cli@2.0
  heroku: circleci/heroku@1.2.6
workflows:
  gh-workflow:
    jobs:
      - create-a-pr:
            context:
               - GITHUB_TOKEN
            filters:
              branches:
                only:
                  - master
      - deploy:
            context:
               - HEROKU_API_KEY
               - HEROKU_PASSWD
               - DOCKERHUB_PASSWD
               - HEROKU_EMAIL






jobs:
  create-a-pr:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - gh/setup
      - run:
          command: |
              git config --global user.name "circleci"
              git config --global user.email "test@test.gg"
              gh pr create -B prod -t "test prod pl" --body "Pull request body"
          name: Create Pull Request For Production
  deploy:
    machine: true
    steps:
      - run: |
         echo "$DOCKERHUB_PASSWD" | docker login --username leesanghyun --password-stdin
      - run:
          command: |
            bash .circleci/setup_heroku.sh


      - checkout
      - run:
          command: |
              if [[ $(command -v heroku) == "" ]]; then
                curl https://cli-assets.heroku.com/install.sh | sh
              else
                echo "Heroku is alread installed. No operation was performed."
              fi
          name: Insatll Heroku CLI (If not installed)
      - run:
          command: |
            heroku container:login
      - run:
          command: |
              docker build \
              -t registry.heroku.com/cafe-backend-app/web \
              --target prod_stage \
              -f ./backend/containers/django/Dockerfile .

              docker build \
              -t registry.heroku.com/squ-cafe/web \
              --target nginx_prod \
              -f ./backend/containers/nginx/Dockerfile .
          name: Build Prod backend, web Image
      - run:
          command: |
            docker push registry.heroku.com/cafe-backend-app/web
            docker push registry.heroku.com/squ-cafe/web
          name: push Docker images to heroku registry

      - run:
          command: |
            heroku container:release web -a squ-cafe
            heroku container:release web -a cafe-backend-app




          
        

  