# Generated by Django 3.2.7 on 2021-09-17 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_like"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="tags",
            new_name="tag",
        ),
    ]
