# Generated by Django 3.2.7 on 2021-09-28 05:07

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_auto_20210928_1127"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="total_like",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
