# Generated by Django 3.2.7 on 2021-10-05 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_auto_20211005_1124"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="postbody",
            table="blog_post_body",
        ),
    ]
