# Generated by Django 3.2.7 on 2021-10-05 13:39

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_alter_postbody_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postbody",
            name="post",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="body",
                to="blog.post",
            ),
        ),
    ]
