# Generated by Django 3.2.8 on 2021-10-05 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_auto_20211006_0445"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="like",
            table="blog_post_like",
        ),
    ]
