# Generated by Django 3.2.5 on 2021-10-06 00:04

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0014_alter_like_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="photo",
            field=models.ImageField(
                blank=True,
                upload_to="images/post/<django.db.models.fields.related.ForeignKey>",
            ),
        ),
    ]
